### PR TITLE
Add driveclaw.ino to ArduinoLibrary

### PR DESCRIPTION
**Pull request by TheAnton205**
This is an example for driving 4 motors using an MPU6050 on a hand. After reading analog values from the MPU6050, if the values reach a specific threshold (such as moving the hand to the left) then the corresponding motor will move left. If the values do not reach any threshold, then no motors will run.

### CODE REVIEW

**Comment by AhmedRaja1** [comment]
@TheAnton205 hey, can you please add some description!

**Review by TheAnton205 — COMMENTED** [review]
This is an example for driving 4 motors using an MPU6050 on a hand. After reading analog values from the MPU6050, if the values reach a specific threshold (such as moving the hand to the left) then the corresponding motor will move left. If the values do not reach any threshold, then no motors will run.

**Comment by TheAnton205** [comment]
> @TheAnton205 hey, can you please add some description!

My apologies, updated!

**Comment by AhmedRaja1** [comment]
@TheAnton205 You have been added to the contributors table! Wohoo ✨✨✨

**Comment by AhmedRaja1** [comment]
@all-contributors please add @TheAnton205 for code

**Comment by AhmedRaja1** [comment]
Please do star the repo!

**Comment by AhmedRaja1** [comment]
@TheAnton205  Please do star the repo!

**Comment by TheAnton205** [comment]
> @TheAnton205 Please do star the repo!

of course!

**Pull request merged**
