### PR TITLE
added template for competitive programming

### PR DESCRIPTION
**Pull request by vasanthnaik**
added a very useful template for the cc purpose kindly check it and merge it

### CODE REVIEW

**Comment by AhmedRaja1** [comment]
Welcome @vasanthnaik to the open source!

**Comment by AhmedRaja1** [comment]
@all-contributors please add @vasanthnaik for code

**Comment by AhmedRaja1** [comment]
Hey, @vasanthnaik you have been added to contribution table below!

**Comment by AhmedRaja1** [comment]
@vasanthnaik do star the repo!

**Comment by vasanthnaik** [comment]
> Hey, @vasanthnaik you have been added to contribution table below!

Thankyou @AhmedRaja1 for adding me I will be seeing to contribute more !!!

**Pull request merged**
