### PR TITLE
Titanic- Machine Learning from Disaster

### PR DESCRIPTION
**Pull request by SudaisAlam**
A machine learning competition's Submission files. The competition is hosted by kaggle for training new ML Engineers.

### CODE REVIEW

**Comment by AhmedRaja1** [comment]
Welcome to Open Source!
Keep doing it like a habit now onwards!

**Comment by AhmedRaja1** [comment]
@all-contibutors please add @SudaisAlam for code

**Comment by AhmedRaja1** [comment]
@all-contributors please add @SudaisAlam for code

**Comment by AhmedRaja1** [comment]
@SudaisAlam please do star the repo!

**Comment by SudaisAlam** [comment]
Sure! @AhmedRaja1

**Pull request merged**
